site_name: The Brain Imaging Data Structure (BIDS)

nav:
  - About: index.md
  - Standards:
    - standards/index.md
    - BIDS Specification:
      - standards/bids_specification/index.md
    - BIDS Stats Model:
      - standards/bids_stats_model/index.md
      - standards/bids_stats_model/integration.md
      - Walkthrough:
        - standards/bids_stats_model/walkthrough/index.md
        - standards/bids_stats_model/walkthrough/part_1.md
      - Examples and Resources:
        - standards/bids_stats_model/examples_and_resources/index.md
        - standards/bids_stats_model/examples_and_resources/default_model.md
      - Specification:
        - standards/bids_stats_model/specification/index.md
        - standards/bids_stats_model/specification/reference.md
      - standards/bids_stats_model/legacy.md
      - standards/bids_stats_model/motivations.md
    - BIDS Schema:
      - standards/bids_schema/index.md
      - standards/bids_schema/details.md
      - How it works:
        - standards/bids_schema/how_it_works/index.md
        - standards/bids_schema/how_it_works/objects.md
        - standards/bids_schema/how_it_works/metadata.md
        - standards/bids_schema/how_it_works/rules.md
    - BIDS Apps:
      - standards/bids_app_specification/index.md
      - standards/bids_app_specification/scope.md
      - standards/bids_app_specification/contributors.md
      - Specification:
        - standards/bids_app_specification/specification/index.md
        - standards/bids_app_specification/specification/examples.md
        - standards/bids_app_specification/specification/inputs.md
        - standards/bids_app_specification/specification/outputs.md
        - standards/bids_app_specification/specification/user_interface.md
        - standards/bids_app_specification/specification/release_notes.md
  - Tools:
    - tools/index.md
    - tools/validator.md
    - tools/bids_apps.md
    - tools/others.md
    - Converters:
      - tools/converters/index.md
      - tools/converters/mri_and_pet.md
      - tools/converters/meeg.md
      - tools/converters/physio.md
      - tools/converters/others.md
  - Collaboration: 
    - collaboration/index.md
    - collaboration/code_of_conduct.md
    - collaboration/governance.md
    - collaboration/contributors.md
    - collaboration/acknowledgments.md
  - Getting Started:
    - getting_started/index.md
    - Folders and Files:
      - getting_started/folders_and_files/index.md
      - getting_started/folders_and_files/derivatives.md
      - getting_started/folders_and_files/folders.md
      - getting_started/folders_and_files/metadata.md
      - getting_started/folders_and_files/files.md
    - Resources:
      - getting_started/resources/index.md
      - getting_started/resources/glossary.md
      - getting_started/resources/dependencies.md
      - getting_started/resources/publications.md
      - getting_started/resources/talks.md
    - BIDS Apps:
      - getting_started/bids_apps/index.md
      - getting_started/bids_apps/tutorial.md
    - Tutorials:
      - getting_started/tutorials/index.md
      - getting_started/tutorials/annotation.md
      - Conversion:
        - getting_started/tutorials/conversion/index.md
        - getting_started/tutorials/conversion/asl.md
        - getting_started/tutorials/conversion/mri.md
        - getting_started/tutorials/conversion/pet.md
        - getting_started/tutorials/conversion/ieeg.md
  - Datasets:
    - datasets/index.md
  - Extensions:
    - extensions/index.md
    - extensions/intro.md
    - extensions/beps.md
    - extensions/guide.md
    - extensions/general_guidelines.md
    - extensions/submission.md
  - FAQ:
    - faq/index.md
    - faq/general.md
    - faq/mri.md
    - faq/eeg.md
    - faq/phenotype.md
    - faq/bids_extensions.md
    - faq/bids_apps.md
  - Blog:
    - blog/index.md
  - Impact: 
    - impact/index.md
  - Contact: 
    - contact/index.md
  - Merchandise: 
    - merch/index.md


theme:
  name: material
  favicon: assets/favicon/favicon.ico
  logo: assets/img/logos/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.tooltips
    - footnotes
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    annotation: material/arrow-right-circle
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: light green
      accent: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

edit_uri: https://github.com/bids-standard/bids-extensions/edit/main/docs/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      anchorlink: true
      toc_depth: 4

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/giscus.js

copyright:
  Copyright &copy; BIDS Contributors - <a
  href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/BIDSstandard/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@bidsstandard
    - icon: simple/bluesky
      link: https://bsky.app/profile/bidsstandard.bsky.social/
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/bids-discussion
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bidsstandard/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCxZUcYfd_nvIVWAbzRB1tlw
